src/Entity/Restorateur.php
<?php

namespace App\Entity;

use App\Repository\RestorateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RestorateurRepository::class)]
class Restorateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $nom = null;

    #[ORM\Column(length: 30)]
    private ?string $prenom = null;

    #[ORM\Column(length: 30)]
    private ?string $username = null;

    #[ORM\Column(length: 50)]
    private ?string $password = null;

    #[ORM\Column]
    private ?int $code_TVA = null;

    #[ORM\Column]
    private ?int $cin = null;

    #[ORM\Column(length: 50)]
    private ?string $adresse = null;

    #[ORM\Column]
    private ?int $tel = null;

    #[ORM\OneToMany(mappedBy: 'restorateur', targetEntity: Resto::class, orphanRemoval: true)]
    private Collection $resto;

    public function __construct()
    {
        $this->resto = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getCodeTVA(): ?int
    {
        return $this->code_TVA;
    }

    public function setCodeTVA(int $code_TVA): self
    {
        $this->code_TVA = $code_TVA;

        return $this;
    }

    public function getCin(): ?int
    {
        return $this->cin;
    }

    public function setCin(int $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTel(): ?int
    {
        return $this->tel;
    }

    public function setTel(int $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    /**
     * @return Collection<int, Resto>
     */
    public function getResto(): Collection
    {
        return $this->resto;
    }

    public function addResto(Resto $resto): self
    {
        if (!$this->resto->contains($resto)) {
            $this->resto->add($resto);
            $resto->setRestorateur($this);
        }

        return $this;
    }

    public function removeResto(Resto $resto): self
    {
        if ($this->resto->removeElement($resto)) {
            // set the owning side to null (unless already changed)
            if ($resto->getRestorateur() === $this) {
                $resto->setRestorateur(null);
            }
        }

        return $this;
    }

  
}

src/Form/RestorateurType.php
<?php

namespace App\Form;

use App\Entity\Restorateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestorateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('username')
            ->add('password')
            ->add('code_TVA')
            ->add('cin')
            ->add('adresse')
            ->add('tel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Restorateur::class,
        ]);
    }
}

src/Controller/RestorateurController.php
<?php

namespace App\Controller;

use App\Entity\Restorateur;
use App\Form\RestorateurType;
use App\Repository\RestorateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/restorateur')]
class RestorateurController extends AbstractController
{
    #[Route('/', name: 'app_restorateur_index', methods: ['GET'])]
    public function index(RestorateurRepository $restorateurRepository): Response
    {
        return $this->render('restorateur/index.html.twig', [
            'restorateurs' => $restorateurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_restorateur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RestorateurRepository $restorateurRepository): Response
    {
        $restorateur = new Restorateur();
        $form = $this->createForm(RestorateurType::class, $restorateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $restorateurRepository->save($restorateur, true);

            return $this->redirectToRoute('app_restorateur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restorateur/new.html.twig', [
            'restorateur' => $restorateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_restorateur_show', methods: ['GET'])]
    public function show(Restorateur $restorateur): Response
    {
        return $this->render('restorateur/show.html.twig', [
            'restorateur' => $restorateur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_restorateur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Restorateur $restorateur, RestorateurRepository $restorateurRepository): Response
    {
        $form = $this->createForm(RestorateurType::class, $restorateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $restorateurRepository->save($restorateur, true);

            return $this->redirectToRoute('app_restorateur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restorateur/edit.html.twig', [
            'restorateur' => $restorateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_restorateur_delete', methods: ['POST'])]
    public function delete(Request $request, Restorateur $restorateur, RestorateurRepository $restorateurRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restorateur->getId(), $request->request->get('_token'))) {
            $restorateurRepository->remove($restorateur, true);
        }

        return $this->redirectToRoute('app_restorateur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/restorateur/_delete_form.html.twig
<form method="post" action="{{ path('app_restorateur_delete', {'id': restorateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restorateur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/restorateur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/restorateur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Restorateur{% endblock %}

{% block body %}
    <h1>Edit Restorateur</h1>

    {{ include('restorateur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_restorateur_index') }}">back to list</a>

    {{ include('restorateur/_delete_form.html.twig') }}
{% endblock %}

templates/restorateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restorateur index{% endblock %}

{% block body %}
    <h1>Restorateur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Username</th>
                <th>Password</th>
                <th>Code_TVA</th>
                <th>Cin</th>
                <th>Adresse</th>
                <th>Tel</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for restorateur in restorateurs %}
            <tr>
                <td>{{ restorateur.id }}</td>
                <td>{{ restorateur.nom }}</td>
                <td>{{ restorateur.prenom }}</td>
                <td>{{ restorateur.username }}</td>
                <td>{{ restorateur.password }}</td>
                <td>{{ restorateur.codeTVA }}</td>
                <td>{{ restorateur.cin }}</td>
                <td>{{ restorateur.adresse }}</td>
                <td>{{ restorateur.tel }}</td>
                <td>
                    <a href="{{ path('app_restorateur_show', {'id': restorateur.id}) }}">show</a>
                    <a href="{{ path('app_restorateur_edit', {'id': restorateur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_restorateur_new') }}">Create new</a>
{% endblock %}

templates/restorateur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Restorateur{% endblock %}

{% block body %}
    <h1>Create new Restorateur</h1>

    {{ include('restorateur/_form.html.twig') }}

    <a href="{{ path('app_restorateur_index') }}">back to list</a>
{% endblock %}

templates/restorateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restorateur{% endblock %}

{% block body %}
    <h1>Restorateur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ restorateur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ restorateur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ restorateur.prenom }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ restorateur.username }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ restorateur.password }}</td>
            </tr>
            <tr>
                <th>Code_TVA</th>
                <td>{{ restorateur.codeTVA }}</td>
            </tr>
            <tr>
                <th>Cin</th>
                <td>{{ restorateur.cin }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ restorateur.adresse }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ restorateur.tel }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_restorateur_index') }}">back to list</a>

    <a href="{{ path('app_restorateur_edit', {'id': restorateur.id}) }}">edit</a>

    {{ include('restorateur/_delete_form.html.twig') }}
{% endblock %}